### ISSUE TITLE
Verifying JWTs with a custom JWKS url or specific key

### ISSUE THREAD

**Issue by biro456** [cfworker/cfworker#111] opened 2021-03-26 23:23 UTC
I'm using Cloudflare Access to secure some backend services and it doesn't serve the JWKS on the `${issuer}/.well-known/jwks.json`.

Currently I can't pass the JWKS url or a standalone `CryptoKey` to either `parseJwt` or `verifyJwtSignature`, so it's not possible to use `@cfworker/jwt` this library to validate them.

Also, it seems that even though `${issuer}/.well-known/jwks.json` is available in several services, it is not mentioned in the [JWK RFC](https://tools.ietf.org/html/rfc7517) neither is it listed in [IANA's Well-Known URIs registry](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml).

**Comment by jdanyow** [comment] 2021-03-28 18:01
As a workaround you can manually import the key using this function:
https://github.com/cfworker/cfworker/blob/c84d1aae24aa3267d8e786c3830e14cb21a9444f/packages/jwt/src/jwks.ts#L20-L25

If you have a CryptoKey instance already, here's the code to export it as a jwk:
```js
const jwk = await crypto.subtle.exportKey('jwk', publicKey);
```

**Comment by m3hari** [comment] 2021-03-29 04:28
@biro456 [This](https://github.com/cfworker/cfworker/issues/89) was an exact same issue 😅

**Comment by jdanyow** [comment] 2021-11-22 15:40
closing as duplicate of https://github.com/cfworker/cfworker/issues/89#issuecomment-743472265

**Closed by jdanyow** 2021-11-22 15:40 UTC
Labels: enhancement
